ALTER TABLE groups ADD COLUMN "date_creation" VARCHAR(25) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE posts ADD COLUMN "date" VARCHAR(25) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE comments ADD COLUMN "date" VARCHAR(25) NOT NULL DEFAULT CURRENT_TIMESTAMP;